package eventmanagementsystem;

import java.sql.PreparedStatement;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author zahid
 */
public class HouseEventOrder extends javax.swing.JFrame {
    String c_id,query,event,edate,etime;
    int w_n=0,w_p,chef_n=0,chef_p,photo_n=0,photo_p,l_n=0,l_p,f_n=0,f_p,chair_n=0,chair_p,t_n=0,t_p,g_n=0,g_p,p_n=0,p_p,t_charge=0,total_cost=0,grandTotal=0;
    int waitertp,cheftp,phototp,chairtp,ttp,gtp,ptp,ftp,ltp;
    /**
     * Creates new form HouseEventOrder
     */
    public HouseEventOrder(String cid,String eventType) {
        initComponents();
        this.c_id=cid;
        this.event=eventType;
        fetchPrice();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        atf = new javax.swing.JTextField();
        dc = new com.toedter.calendar.JDateChooser();
        wtf = new javax.swing.JTextField();
        ctf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ltf = new javax.swing.JTextField();
        chtf = new javax.swing.JTextField();
        ttf = new javax.swing.JTextField();
        gtf = new javax.swing.JTextField();
        pstf = new javax.swing.JTextField();
        tc = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        ptf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ftf = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        wtp = new javax.swing.JLabel();
        cp = new javax.swing.JLabel();
        photoP = new javax.swing.JLabel();
        lp = new javax.swing.JLabel();
        fp = new javax.swing.JLabel();
        chp = new javax.swing.JLabel();
        tp = new javax.swing.JLabel();
        gp = new javax.swing.JLabel();
        psp = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        gt = new javax.swing.JLabel();
        t_cost = new javax.swing.JLabel();
        t_c = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(9, 132, 227));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("House Event Order");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel1)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Address :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Date :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Time :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Waiters :");

        jLabel6.setText("Chefs :");

        atf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atfActionPerformed(evt);
            }
        });

        wtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wtfActionPerformed(evt);
            }
        });
        wtf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                wtfKeyReleased(evt);
            }
        });

        ctf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctfActionPerformed(evt);
            }
        });
        ctf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ctfKeyReleased(evt);
            }
        });

        jLabel8.setText("Chairs :");

        jLabel9.setText("Tables :");

        jLabel10.setText("Glasses :");

        jLabel11.setText("Plates :");

        ltf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ltfActionPerformed(evt);
            }
        });
        ltf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ltfKeyReleased(evt);
            }
        });

        chtf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                chtfKeyReleased(evt);
            }
        });

        ttf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ttfKeyReleased(evt);
            }
        });

        gtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gtfActionPerformed(evt);
            }
        });
        gtf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gtfKeyReleased(evt);
            }
        });

        pstf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pstfKeyReleased(evt);
            }
        });

        tc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afternoon", "Evening" }));
        tc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcActionPerformed(evt);
            }
        });

        jLabel12.setText("Photographers: ");

        ptf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptfActionPerformed(evt);
            }
        });
        ptf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ptfKeyReleased(evt);
            }
        });

        jLabel7.setText("Flowers :");

        jLabel13.setText("Lighting :");

        ftf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfActionPerformed(evt);
            }
        });
        ftf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ftfKeyReleased(evt);
            }
        });

        jLabel15.setText("Price");

        wtp.setText("0");

        cp.setText("0");

        photoP.setText("0");

        lp.setText("0");

        fp.setText("0");

        chp.setText("0");

        tp.setText("0");

        gp.setText("0");

        psp.setText("0");

        jLabel26.setText("Total Cost :");

        jLabel27.setText("Total Charge :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Grand Total :");

        gt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gt.setText("0");

        t_cost.setText("0");

        t_c.setText("0");

        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setForeground(new java.awt.Color(9, 132, 227));
        jButton2.setText("Confirm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(atf, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(dc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(wtf, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                            .addComponent(ctf)
                                            .addComponent(ptf))
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(photoP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(t_c, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(wtp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jLabel27))))
                        .addGap(114, 114, 114)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel10)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(jLabel13)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(8, 8, 8)))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(gtf)
                            .addComponent(pstf)
                            .addComponent(ttf)
                            .addComponent(chtf)
                            .addComponent(ftf)
                            .addComponent(jLabel26)
                            .addComponent(ltf))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(psp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t_cost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15)
                            .addComponent(lp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(46, 46, 46)
                        .addComponent(gt, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(244, 244, 244))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(102, 102, 102))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(atf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(ltf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lp))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(ftf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fp))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chp))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(wtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(ttf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wtp)
                    .addComponent(tp))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ctf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(gtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cp)
                    .addComponent(gp))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(pstf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(ptf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(photoP)
                    .addComponent(psp))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(t_cost)
                    .addComponent(t_c))
                .addGap(19, 19, 19)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gt)
                    .addComponent(jLabel14))
                .addGap(15, 15, 15)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void fetchPrice(){
        sqlConnect co = new sqlConnect();
        co.connectDB();
        query="Select *from priceList ";
        try{
            co.resultSet = co.statement.executeQuery(query);
            if(co.resultSet.next()){
                w_p=co.resultSet.getInt("Waiters_p");
                chef_p=co.resultSet.getInt("Chefs_p");
                photo_p=co.resultSet.getInt("Photographer_p");
                chair_p=co.resultSet.getInt("Chairs_p");
                t_p=co.resultSet.getInt("diningTable_p");
                
                g_p=co.resultSet.getInt("Glasses_p");
                p_p=co.resultSet.getInt("Plates_p");
            }
             query="Select *from decorationPriceList";
             co.resultSet = co.statement.executeQuery(query);
            if(co.resultSet.next()){
                l_p=co.resultSet.getInt("lights_p");
                f_p=co.resultSet.getInt("flowers_p");
               
            }
             
        }catch(Exception e){
            
        }
        
    }
    private void atfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atfActionPerformed

    private void ltfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ltfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ltfActionPerformed

    private void tcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcActionPerformed

    private void wtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wtfActionPerformed

    private void ctfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctfActionPerformed

    private void gtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gtfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new OrderType(c_id).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ftfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfActionPerformed

    private void ptfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ptfActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       sqlConnect co = new sqlConnect();
        co.connectDB(); 
       
        try{
          if(atf.getText().isEmpty()||dc.getDate()==null){
             JOptionPane.showMessageDialog(this, "Address, date and time required"); 
             return; 
          }
        SimpleDateFormat sdf =new SimpleDateFormat("yyyy-MM-dd");
        edate=sdf.format(dc.getDate());
        etime=tc.getSelectedItem().toString();
        query="insert into Orders (Event_type,C_ID,Waiters,Chefs,Photographer,Chairs,diningTable,Glasses,Plates,O_Date,O_Time,lights,flowers,totalAmount,Event_address) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst = co.connection.prepareStatement(query);
            pst.setString(1, event);
            pst.setInt(2, Integer.parseInt(c_id));
            pst.setInt(3, w_n);
            pst.setInt(4, chef_n);
            pst.setInt(5, photo_n);
            pst.setInt(6, chair_n);
            pst.setInt(7, t_n);
            pst.setInt(8, g_n);
            pst.setInt(9, p_n);
            pst.setString(10, edate);
            pst.setString(11, etime);
            pst.setInt(12, l_n);
            pst.setInt(13,f_n);
            pst.setInt(14,grandTotal);          
            pst.setString(15,atf.getText());
            pst.executeUpdate();
        JOptionPane.showMessageDialog(this,"Order placed successfully! Please wait for confirmation");     
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void wtfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wtfKeyReleased
        // TODO add your handling code here:
        if(wtf.getText().length()>0){
        if(wtf.getText().charAt(wtf.getText().length()-1)>='0' && wtf.getText().charAt(wtf.getText().length()-1)<='9'){
            w_n=Integer.parseInt(wtf.getText());
            waitertp=w_n*w_p;
            wtp.setText(waitertp+"");
        }else
        {
            waitertp=0;
            wtp.setText(waitertp+"");
            wtf.setText("");
            JOptionPane.showMessageDialog(this, "Only Numerica Value allowed");
        }
        }
        else
        {   
             waitertp=0;
             wtp.setText(waitertp+"");
        }
        t_charge=waitertp+cheftp+phototp;
        t_c.setText(t_charge+"");
        grandTotal=t_charge+total_cost;
        gt.setText(grandTotal+"");
    }//GEN-LAST:event_wtfKeyReleased

    private void ctfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ctfKeyReleased
        // TODO add your handling code here:
        if(ctf.getText().length()>0){
        if(ctf.getText().charAt(ctf.getText().length()-1)>='0' && ctf.getText().charAt(ctf.getText().length()-1)<='9'){
            chef_n=Integer.parseInt(ctf.getText());
            cheftp=chef_n*chef_p;
            cp.setText(cheftp+"");
        }else
        {
            cheftp=0;
            cp.setText(cheftp+"");
            ctf.setText("");
            JOptionPane.showMessageDialog(this, "Only Numerica Value allowed");
        }
        }
        else
        {   
             cheftp=0;
             cp.setText(cheftp+"");
        }
        t_charge=waitertp+cheftp+phototp;
        t_c.setText(t_charge+"");
        grandTotal=t_charge+total_cost;
        gt.setText(grandTotal+"");
    }//GEN-LAST:event_ctfKeyReleased

    private void ptfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ptfKeyReleased
        // TODO add your handling code here:
        if(ptf.getText().length()>0){
        if(ptf.getText().charAt(ptf.getText().length()-1)>='0' && ptf.getText().charAt(ptf.getText().length()-1)<='9'){
            photo_n=Integer.parseInt(ptf.getText());
            phototp=photo_n*photo_p;
            photoP.setText(phototp+"");
        }else
        {
            phototp=0;
            photoP.setText(phototp+"");
            ptf.setText("");
            JOptionPane.showMessageDialog(this, "Only Numerica Value allowed");
        }
        }
        else
        {   
             phototp=0;
             photoP.setText(phototp+"");
        }
        t_charge=waitertp+cheftp+phototp;
        t_c.setText(t_charge+"");
        grandTotal=t_charge+total_cost;
        gt.setText(grandTotal+"");
    }//GEN-LAST:event_ptfKeyReleased

    private void ltfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ltfKeyReleased
        // TODO add your handling code here:
        if(ltf.getText().length()>0){
        if(ltf.getText().charAt(ltf.getText().length()-1)>='0' && ltf.getText().charAt(ltf.getText().length()-1)<='9'){
            l_n=Integer.parseInt(ltf.getText());
            ltp=l_n*l_p;
            lp.setText(ltp+"");
        }else
        {
            ltp=0;
            lp.setText(ltp+"");
            ltf.setText("");
            JOptionPane.showMessageDialog(this, "Only Numerica Value allowed");
        }
        }
        else
        {   
             ltp=0;
             lp.setText(ltp+"");
        }
        total_cost=ltp+ftp+gtp+ptp+chairtp+ttp;
        t_cost.setText(total_cost+"");
        grandTotal=t_charge+total_cost;
        gt.setText(grandTotal+""); 
    }//GEN-LAST:event_ltfKeyReleased

    private void ftfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftfKeyReleased
        // TODO add your handling code here:
        if(ftf.getText().length()>0){
        if(ftf.getText().charAt(ftf.getText().length()-1)>='0' && ftf.getText().charAt(ftf.getText().length()-1)<='9'){
            f_n=Integer.parseInt(ftf.getText());
            ftp=f_n*f_p;
            fp.setText(ftp+"");
        }else
        {
            ftp=0;
            fp.setText(ftp+"");
            ftf.setText("");
            JOptionPane.showMessageDialog(this, "Only Numerica Value allowed");
        }
        }
        else
        {   
             ftp=0;
             fp.setText(ftp+"");
        }
        total_cost=ltp+ftp+gtp+ptp+chairtp+ttp;
        t_cost.setText(total_cost+"");
        grandTotal=t_charge+total_cost;
        gt.setText(grandTotal+""); 
    }//GEN-LAST:event_ftfKeyReleased

    private void chtfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chtfKeyReleased
        // TODO add your handling code here
        if(chtf.getText().length()>0){
        if(chtf.getText().charAt(chtf.getText().length()-1)>='0' && chtf.getText().charAt(chtf.getText().length()-1)<='9'){
            chair_n=Integer.parseInt(chtf.getText());
            chairtp=chair_n*chair_p;
            chp.setText(chairtp+"");
        }else
        {
            chairtp=0;
            chp.setText(chairtp+"");
            chtf.setText("");
            JOptionPane.showMessageDialog(this, "Only Numerica Value allowed");
        }
        }
        else
        {   
             chairtp=0;
             chp.setText(chairtp+"");
        }
        total_cost=ltp+ftp+gtp+ptp+chairtp+ttp;
        t_cost.setText(total_cost+"");
        grandTotal=t_charge+total_cost;
        gt.setText(grandTotal+""); 
    }//GEN-LAST:event_chtfKeyReleased

    private void ttfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ttfKeyReleased
        // TODO add your handling code here:
         if(ttf.getText().length()>0){
        if(ttf.getText().charAt(ttf.getText().length()-1)>='0' && ttf.getText().charAt(ttf.getText().length()-1)<='9'){
            t_n=Integer.parseInt(ttf.getText());
            ttp=t_n*t_p;
            tp.setText(ttp+"");
        }else
        {
            ttp=0;
            tp.setText(ttp+"");
            ttf.setText("");
            JOptionPane.showMessageDialog(this, "Only Numerica Value allowed");
        }
        }
        else
        {   
             ttp=0;
             tp.setText(ttp+"");
        }
        total_cost=ltp+ftp+gtp+ptp+chairtp+ttp;
        t_cost.setText(total_cost+"");
        grandTotal=t_charge+total_cost;
        gt.setText(grandTotal+""); 
    }//GEN-LAST:event_ttfKeyReleased

    private void gtfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gtfKeyReleased
        // TODO add your handling code here:
         if(gtf.getText().length()>0){
        if(gtf.getText().charAt(gtf.getText().length()-1)>='0' && gtf.getText().charAt(gtf.getText().length()-1)<='9'){
            g_n=Integer.parseInt(gtf.getText());
            gtp=g_n*g_p;
            gp.setText(gtp+"");
        }else
        {
            gtp=0;
            gp.setText(gtp+"");
            gtf.setText("");
            JOptionPane.showMessageDialog(this, "Only Numerica Value allowed");
        }
        }
        else
        { 
          gtp=0;
          gp.setText(gtp+"");  
        }  
             
        total_cost=ltp+ftp+gtp+ptp+chairtp+ttp;
        t_cost.setText(total_cost+"");
        grandTotal=t_charge+total_cost;
        gt.setText(grandTotal+""); 
             
    }//GEN-LAST:event_gtfKeyReleased

    private void pstfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pstfKeyReleased
        // TODO add your handling code here:
         if(pstf.getText().length()>0){
        if(pstf.getText().charAt(pstf.getText().length()-1)>='0' && pstf.getText().charAt(pstf.getText().length()-1)<='9'){
            p_n=Integer.parseInt(pstf.getText());
            ptp=p_n*p_p;
            psp.setText(ptp+"");
        }else
        {
            ptp=0;
            psp.setText(ptp+"");
            pstf.setText("");
            JOptionPane.showMessageDialog(this, "Only Numerica Value allowed");
        }
        }
        else
        {   
              ptp=0;
              psp.setText(ptp+"");
        }
        total_cost=ltp+ftp+gtp+ptp+chairtp+ttp;
        t_cost.setText(total_cost+"");
        grandTotal=t_charge+total_cost;
        gt.setText(grandTotal+""); 
    }//GEN-LAST:event_pstfKeyReleased

    /**
     * @param/**
 args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HouseEventOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HouseEventOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HouseEventOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HouseEventOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HouseEventOrder("1","1").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField atf;
    private javax.swing.JLabel chp;
    private javax.swing.JTextField chtf;
    private javax.swing.JLabel cp;
    private javax.swing.JTextField ctf;
    private com.toedter.calendar.JDateChooser dc;
    private javax.swing.JLabel fp;
    private javax.swing.JTextField ftf;
    private javax.swing.JLabel gp;
    private javax.swing.JLabel gt;
    private javax.swing.JTextField gtf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lp;
    private javax.swing.JTextField ltf;
    private javax.swing.JLabel photoP;
    private javax.swing.JLabel psp;
    private javax.swing.JTextField pstf;
    private javax.swing.JTextField ptf;
    private javax.swing.JLabel t_c;
    private javax.swing.JLabel t_cost;
    private javax.swing.JComboBox<String> tc;
    private javax.swing.JLabel tp;
    private javax.swing.JTextField ttf;
    private javax.swing.JTextField wtf;
    private javax.swing.JLabel wtp;
    // End of variables declaration//GEN-END:variables
}
